from __future__ import annotations


MODE_COMPANION = "companion"
MODE_INTERACTIVE = "interactive"
MODE_TEACHING = "teaching"
# Legacy operation alias, not a study mode. Keep it separate from SUPPORTED_MODES.
MODE_CONCEPT_EXPLAIN = "concept_explain"

LLM_OPERATION_CONCEPT_EXPLAIN = MODE_CONCEPT_EXPLAIN
LLM_OPERATION_QUESTION_GENERATE = "question_generate"
LLM_OPERATION_ANSWER_EVALUATE = "answer_evaluate"
LLM_OPERATION_KNOWLEDGE_TRACK = "knowledge_track"
LLM_OPERATION_SUMMARIZE_SESSION = "summarize_session"
LLM_OPERATION_EXPAND_NOTE = "expand_note"
LLM_OPERATION_SUMMARIZE_TO_NOTE = "summarize_to_note"

SUPPORTED_LLM_OPERATIONS = frozenset(
    {
        LLM_OPERATION_CONCEPT_EXPLAIN,
        LLM_OPERATION_QUESTION_GENERATE,
        LLM_OPERATION_ANSWER_EVALUATE,
        LLM_OPERATION_KNOWLEDGE_TRACK,
        LLM_OPERATION_SUMMARIZE_SESSION,
        LLM_OPERATION_EXPAND_NOTE,
        LLM_OPERATION_SUMMARIZE_TO_NOTE,
    }
)

SUPPORTED_MODES = frozenset({MODE_COMPANION, MODE_INTERACTIVE, MODE_TEACHING})
